<a href="https://colab.research.google.com/github/iprasantmohanty/FSDSPRO/blob/main/FSDSPRO_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## importing numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

*   numpy is an array which stores the data
*   It stores only same type of data

## creating numpy array

In [4]:
l=[1,2,3,4,5]

In [5]:
type(l)

list

In [6]:
l

[1, 2, 3, 4, 5]

In [7]:
l1=np.array(l)

In [8]:
l1

array([1, 2, 3, 4, 5])

In [9]:
type(l1)

numpy.ndarray

In [10]:
l2=[2,'h',3,4.5]

In [11]:
l3=np.array(l2)

In [12]:
l3

array(['2', 'h', '3', '4.5'], dtype='<U32')

In [13]:
l3.ndim #to show the dimension

1

## creating 2-D array

In [14]:
l4=np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
l4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
l4.ndim

2

## creating matrix

In [17]:
l5=[1,2,3,4]
l6=np.matrix(l5) #by default matrix is 2-d only

In [18]:
l6

matrix([[1, 2, 3, 4]])

In [19]:
type(l6)

numpy.matrix

In [20]:
l6.ndim

2

## creating array using np.asarray()

In [21]:
l7=np.asarray([[1,2],[3,4],[5,6]]) #convert into array , it is same as np.array()
l7

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
type(l7)

numpy.ndarray

## converting using np.asanyarray()

In [23]:
l8=np.asanyarray([[1,2],[3,4],[5,6]])

In [24]:
l8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
type(l8)

numpy.ndarray

In [26]:
l6

matrix([[1, 2, 3, 4]])

In [27]:
l9=np.asanyarray(l6)

In [28]:
l9

matrix([[1, 2, 3, 4]])

In [29]:
type(l9)

numpy.matrix

*   np.asanyarray() doest't convert an matrix to array
*   it remain as matrix

## converting tuple to an array

In [30]:
t1=([1,2,3],[4,5,6])

In [31]:
t1

([1, 2, 3], [4, 5, 6])

In [32]:
type(t1)

tuple

In [33]:
l10=np.asanyarray(t1)

In [34]:
l10

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
type(l10)

numpy.ndarray

## shallow copy vs deep copy



In [36]:
arr=np.array([1,2,3,4,5])

In [37]:
arr

array([1, 2, 3, 4, 5])

In [38]:
a=arr #shallow copy both have same reference

In [39]:
a

array([1, 2, 3, 4, 5])

In [40]:
arr[3]=99

In [41]:
arr

array([ 1,  2,  3, 99,  5])

In [42]:
a #a[3] will also change as arr[3] changes

array([ 1,  2,  3, 99,  5])

In [43]:
b=a.copy() ##deep copy

In [44]:
b

array([ 1,  2,  3, 99,  5])

In [45]:
b[0]=1000

In [46]:
b #change in b[0]

array([1000,    2,    3,   99,    5])

In [47]:
a #but a[0] n't updated

array([ 1,  2,  3, 99,  5])

##generating array

In [48]:
a2=np.fromfunction(lambda i,j :i==j,shape=(3,4))

In [49]:
a2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [50]:
a.shape #its one dimension

(5,)

In [51]:
a2.shape #rows=3, cols=4

(3, 4)

In [52]:
a3=np.fromfunction(lambda i,j :i*j,shape=(3,4))

In [53]:
a3

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [54]:
a4=np.fromiter((i*i for i in range(5)),int)

In [55]:
a4

array([ 0,  1,  4,  9, 16])

In [56]:
a5=np.fromiter(range(5),float)

In [57]:
a5

array([0., 1., 2., 3., 4.])

In [58]:
a6=np.fromstring('10 20 30',sep=' ')

In [59]:
a6

array([10., 20., 30.])

In [60]:
a7=np.fromstring('10,20,30',sep=',')

In [61]:
a7

array([10., 20., 30.])

In [62]:
a7.dtype #datatupe of elements of array

dtype('float64')

*   demerit of range - it can use only int


In [63]:
a8=np.arange(0.3,10.2) #default increment is 1

In [64]:
a8

array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3])

In [65]:
a9=np.arange(0.3,10.2,0.2) #increment set to 0.2

In [66]:
a9

array([ 0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,  2.3,
        2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,  4.5,
        4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,  6.7,
        6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,  8.9,
        9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [67]:
a9.dtype

dtype('float64')

In [68]:
a10=np.linspace(1,5,20) #give 20 float values in between 1 to 5

In [69]:
a10

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [70]:
a11=np.logspace(1,5,20, base=2) #give 20 float values in between 1 to 5

In [71]:
a11

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [72]:
a12=np.zeros(5)
a12

array([0., 0., 0., 0., 0.])

In [73]:
a13=np.zeros((3,4))
a13

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
a14=np.zeros((2,3,4)) #repeat 2-d array(3,4) 2 times #its 3-d
a14

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [75]:
a14.shape

(2, 3, 4)

In [76]:
a14.ndim

3

In [77]:
a14=np.ones((3,4))
a14

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
a14+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [79]:
a14*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [80]:
a15=np.empty((3,4)) #create a random numpy array, by default float value
a15

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [81]:
a16=np.empty((3,4),int) #create a random numpy array, by default float value
a16

array([[4611686018427387904, 4611686018427387904, 4611686018427387904,
        4611686018427387904],
       [4611686018427387904, 4611686018427387904, 4611686018427387904,
        4611686018427387904],
       [4611686018427387904, 4611686018427387904, 4611686018427387904,
        4611686018427387904]])

In [82]:
a17=np.eye(4) #create an identity matrix, its a square matrix
a17

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random number generation

In [83]:
import random

In [84]:
random.choice((1,2,3,4,5,6)) #random generation of a dice

1

In [85]:
random.choice("prasant") #generate a random character from the string

'p'

In [86]:
random.randrange(1,100) #generate a random number between 1 to 10

99

In [87]:
random.random()

0.1268916837971089

In [88]:
l1=[1,2,3,4,5]
l1

[1, 2, 3, 4, 5]

In [89]:
random.shuffle(l1) #shuffle the list elements
l1

[2, 1, 3, 5, 4]

In [90]:
random.uniform(7,14) #generate a float between 7 to 14

11.223784991458592

In [91]:
np.random.rand() #generate a single random number

0.4493794132522886

In [92]:
np.random.rand(2,3) #generate matrix of random numbers

array([[0.69910947, 0.98036634, 0.23535574],
       [0.3934465 , 0.32759063, 0.48178673]])

In [93]:
np.random.random_sample()

0.40560411991467726

In [94]:
arr=np.random.randint(1,5,size=(3,4)) #generate random matrix in between 1 to 5 of size

In [95]:
arr

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

## reshaping array

In [96]:
arr.size #total no of elements in the array

12

In [97]:
arr.shape

(3, 4)

In [98]:
arr.ndim

2

In [99]:
arr

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

In [100]:
arr.reshape(2,6)

array([[1, 3, 4, 3, 2, 3],
       [1, 2, 3, 1, 1, 4]])

In [101]:
arr.reshape(4,3)

array([[1, 3, 4],
       [3, 2, 3],
       [1, 2, 3],
       [1, 1, 4]])

In [102]:
arr.reshape(6,2)

array([[1, 3],
       [4, 3],
       [2, 3],
       [1, 2],
       [3, 1],
       [1, 4]])

In [103]:
arr.reshape(12,)

array([1, 3, 4, 3, 2, 3, 1, 2, 3, 1, 1, 4])

In [104]:
arr.reshape(4,-1) #when num of cols is unknown

array([[1, 3, 4],
       [3, 2, 3],
       [1, 2, 3],
       [1, 1, 4]])

In [105]:
arr.reshape(3,-1) #when num of cols is unknown

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

In [106]:
arr.reshape(-1,4) #when num of rows is unknown

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

In [107]:
arr.reshape(4,-1).base #return the base (original) array

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

In [108]:
arr

array([[1, 3, 4, 3],
       [2, 3, 1, 2],
       [3, 1, 1, 4]])

In [109]:
arr.reshape(2,2,3) #create 3 dim array

array([[[1, 3, 4],
        [3, 2, 3]],

       [[1, 2, 3],
        [1, 1, 4]]])

In [110]:
arr.reshape(3,2,2)

array([[[1, 3],
        [4, 3]],

       [[2, 3],
        [1, 2]],

       [[3, 1],
        [1, 4]]])

In [111]:
arr1=np.random.randint(1,10,(5,6))

In [112]:
arr1

array([[2, 4, 8, 5, 3, 7],
       [3, 9, 1, 4, 9, 4],
       [2, 4, 2, 4, 8, 1],
       [8, 2, 5, 2, 5, 7],
       [1, 2, 9, 6, 5, 4]])

In [113]:
arr1>5 #it shows which set of elements >5 or not

array([[False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [False, False, False, False,  True, False],
       [ True, False, False, False, False,  True],
       [False, False,  True,  True, False, False]])

In [114]:
arr2=arr1[arr1>5] #create a new array by picking only those elements of arr1 >5

In [115]:
arr2 #change arr2 to 1 dim

array([8, 7, 9, 9, 8, 8, 7, 9, 6])

In [116]:
arr2.shape

(9,)

In [117]:
arr1

array([[2, 4, 8, 5, 3, 7],
       [3, 9, 1, 4, 9, 4],
       [2, 4, 2, 4, 8, 1],
       [8, 2, 5, 2, 5, 7],
       [1, 2, 9, 6, 5, 4]])

## indexing and slicing array

In [118]:
arr1[1] #2nd row

array([3, 9, 1, 4, 9, 4])

In [119]:
arr1[0][2]

8

In [120]:
arr1[0,1:3] #elements from 0th row and 1 and 2 col

array([4, 8])

In [121]:
arr1[:,1:3] #1 and 2 col of all rows

array([[4, 8],
       [9, 1],
       [4, 2],
       [2, 5],
       [2, 9]])

In [122]:
arr1[2:4] #only 2 and 3 row

array([[2, 4, 2, 4, 8, 1],
       [8, 2, 5, 2, 5, 7]])

In [123]:
arr1[2:5,:2] #row 2,3,4 and col 0,1

array([[2, 4],
       [8, 2],
       [1, 2]])

In [124]:
arr1

array([[2, 4, 8, 5, 3, 7],
       [3, 9, 1, 4, 9, 4],
       [2, 4, 2, 4, 8, 1],
       [8, 2, 5, 2, 5, 7],
       [1, 2, 9, 6, 5, 4]])

In [125]:
arr1[[1,3],[1,4]] # return element of row,col=1,1 and row,col=3,4

array([9, 5])

In [126]:
arr1[[2,4]] #only row 1 and 4

array([[2, 4, 2, 4, 8, 1],
       [1, 2, 9, 6, 5, 4]])

In [127]:
arr1[2:4] #from row 2 to previous of 4 (i.e. 3)

array([[2, 4, 2, 4, 8, 1],
       [8, 2, 5, 2, 5, 7]])

## array operation

In [128]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [129]:
arr1

array([[2, 2, 2],
       [1, 2, 2],
       [2, 1, 2]])

In [130]:
arr2

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [131]:
arr1+arr2 #index wise addition

array([[3, 4, 4],
       [2, 3, 3],
       [4, 2, 3]])

In [132]:
arr1*arr2 #index wise multiplication (not matrix multiplication)

array([[2, 4, 4],
       [1, 2, 2],
       [4, 1, 2]])

In [133]:
arr1 @ arr2 #matrix multiplication

array([[8, 8, 8],
       [7, 6, 6],
       [7, 7, 7]])

In [134]:
arr1/arr2 #index-wise division

array([[2., 1., 1.],
       [1., 2., 2.],
       [1., 1., 2.]])

In [135]:
arr1/0

<ipython-input-135-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

##broadcasting

doing some operation to all elements of the array

In [136]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [138]:
a=np.array([1,2,3,4])

In [139]:
arr+a #each index of a will be broadcasted (and added) to each index of arr as well as each row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [140]:
b=np.array([1,2,3]).reshape((3,1))
b

array([[1],
       [2],
       [3]])

In [141]:
arr+b #broadcasted column-wise

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [142]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [143]:
c.T #1-dim array can't do transpose

array([1, 2, 3])

In [144]:
c=np.array([[1,2,3]]) #now array is 2-dim
c

array([[1, 2, 3]])

In [145]:
c.T #2-dim now can do transpose

array([[1],
       [2],
       [3]])

In [146]:
arr+c.T #column wise addition is done

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

## array operations

In [147]:
np.sqrt(arr+c.T)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [148]:
np.log10(arr+c.T)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125]])

In [149]:
np.exp(arr+c.T)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692]])

In [150]:
np.min(arr+c.T)

1.0

## changing dimesion of array

In [151]:
arr=np.random.randint(1,5,(3,3))

In [152]:
arr

array([[3, 3, 3],
       [3, 4, 2],
       [4, 4, 3]])

In [153]:
arr.flatten()  #reduce the higher dimension to 1-D

array([3, 3, 3, 3, 4, 2, 4, 4, 3])

In [154]:
arr

array([[3, 3, 3],
       [3, 4, 2],
       [4, 4, 3]])



*   row-wise --> axis=0
*   col-wise --> axis=1




In [155]:
np.sum(arr)

29

In [156]:
np.sum(arr,axis=0) #row-wise addition

array([10, 11,  8])

In [157]:
np.sum(arr,axis=1) #col-wise addition

array([ 9,  9, 11])

In [158]:
#expand the array by inserting a new axis

In [159]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [160]:
arr1.ndim

1

In [161]:
arr1.shape

(4,)

In [162]:
arr2=np.expand_dims(arr1,axis=0)
arr2

array([[1, 2, 3, 4]])

In [163]:
arr2.ndim

2

In [164]:
arr3=np.expand_dims(arr2,axis=0)
arr3

array([[[1, 2, 3, 4]]])

In [165]:
arr3.ndim

3

In [166]:
arr4=np.expand_dims(arr1,axis=1)
arr4

array([[1],
       [2],
       [3],
       [4]])

In [167]:
arr4.ndim

2

In [168]:
arr4.shape

(4, 1)

In [169]:
data=np.array([[1],[2],[3]])

In [170]:
data.ndim

2

In [171]:
data

array([[1],
       [2],
       [3]])

In [172]:
data.shape

(3, 1)

In [173]:
a=np.squeeze(data) #reduce dimension

In [174]:
a

array([1, 2, 3])

In [175]:
a.ndim

1

In [176]:
a.shape

(3,)

In [177]:
np.repeat(data,4) #data is repeated 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [178]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [179]:
c=np.repeat(b,2)
c

array([1, 1, 2, 2, 3, 3, 4, 4])

In [180]:
c.reshape(2,4)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [181]:
c=np.repeat(b,2,axis=1) #it repeat col-wise , so dont need reshape
c

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [182]:
c=np.repeat(b,3,axis=0) #it repeat row-wise 3times , so dont need reshape
c

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [183]:
data

array([[1],
       [2],
       [3]])

In [184]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [185]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [186]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [187]:
np.diag(np.array([1,2,3,4])) #create diagnal matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [188]:
a=np.array([[[1,2],[3,4],[5,6]]])
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [189]:
np.roll(a,1,axis=1)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [190]:
arr1=np.random.randint(1,10,(3,4))
arr1

array([[6, 1, 5, 5],
       [6, 2, 7, 4],
       [4, 3, 2, 9]])

In [191]:
arr2=np.random.randint(1,10,(3,4))
arr2

array([[5, 9, 5, 7],
       [4, 1, 7, 6],
       [4, 5, 4, 4]])

## string operations

In [192]:
arr=np.array(["prasant","mohanty"])
arr

array(['prasant', 'mohanty'], dtype='<U7')

In [193]:
np.char.upper(arr)

array(['PRASANT', 'MOHANTY'], dtype='<U7')

In [194]:
np.char.capitalize(arr)

array(['Prasant', 'Mohanty'], dtype='<U7')

In [195]:
np.char.title(arr)

array(['Prasant', 'Mohanty'], dtype='<U7')

## math functions

In [196]:
arr1=np.random.randint(1,10,(3,4))
arr1

array([[1, 5, 3, 9],
       [2, 5, 2, 9],
       [6, 5, 5, 9]])

In [197]:
np.sin(arr1)

array([[ 0.84147098, -0.95892427,  0.14112001,  0.41211849],
       [ 0.90929743, -0.95892427,  0.90929743,  0.41211849],
       [-0.2794155 , -0.95892427, -0.95892427,  0.41211849]])

In [198]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219, -0.9899925 , -0.91113026],
       [-0.41614684,  0.28366219, -0.41614684, -0.91113026],
       [ 0.96017029,  0.28366219,  0.28366219, -0.91113026]])

In [199]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.47712125, 0.95424251],
       [0.30103   , 0.69897   , 0.30103   , 0.95424251],
       [0.77815125, 0.69897   , 0.69897   , 0.95424251]])

In [200]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 2.00855369e+01, 8.10308393e+03],
       [7.38905610e+00, 1.48413159e+02, 7.38905610e+00, 8.10308393e+03],
       [4.03428793e+02, 1.48413159e+02, 1.48413159e+02, 8.10308393e+03]])

In [201]:
arr1

array([[1, 5, 3, 9],
       [2, 5, 2, 9],
       [6, 5, 5, 9]])

In [202]:
np.power(arr1,2)

array([[ 1, 25,  9, 81],
       [ 4, 25,  4, 81],
       [36, 25, 25, 81]])

In [203]:
arr=np.array([4,2,6,1,7])
arr

array([4, 2, 6, 1, 7])

In [204]:
np.sort(arr)

array([1, 2, 4, 6, 7])

In [205]:
np.count_nonzero(arr)

5

In [206]:
arr

array([4, 2, 6, 1, 7])

In [207]:
np.where(arr>2)#return index of elements where condition is true

(array([0, 2, 4]),)

## matrix library

In [208]:
import numpy.matlib as nm

In [209]:
nm.zeros((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [210]:
nm.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [211]:
A=np.random.randint(1,10,(3,3)) #let it is A of equation Ax=B
A

array([[5, 3, 9],
       [2, 8, 4],
       [7, 1, 9]])

In [212]:
B=np.array([16,-8,0])
B

array([16, -8,  0])

In [213]:
np.linalg.solve(A,B) #it is solution x

array([-10.62068966,  -2.62068966,   8.55172414])

In [214]:
np.linalg.det(A) #determinant of matrix A

-116.00000000000009

In [215]:
np.linalg.inv(A) #inverse of matrix A

array([[-0.5862069 ,  0.15517241,  0.51724138],
       [-0.0862069 ,  0.15517241,  0.01724138],
       [ 0.46551724, -0.13793103, -0.29310345]])